import { FormGroup } from '@angular/forms';
import { JobPartModel } from '../parts/job-part.model';
import { JobType } from '../jobtype/job-type.model';

export class JobModel {
    id = 0;
    customerName: string = null;
    customerAddress: string = null;
    customerPhone: string = null;
    dateStarted: Date;
    dateFinished: Date;
    bidAcceptedDate: Date;
    jobActiveDate: Date;
    jobInvoiceDate: Date;
    active: boolean;
    invoiced: boolean;
    readyToBill: boolean;
    notes: string;
    HangWorkerId: number;
    HangStatusId: number;
    FinishWorkerId: number;
    FinishStatusId: number;
    SprayWorkerId: number;
    SprayStatusId: number;
    StockWorkerId: number;
    StockStatusId: number;
    MeasureWorkerId: number;
    MeasureStatusId: number;
    OrderWorkerId: number;
    OrderStatusId: number;
    SetWorkerId: number;
    SetStatusId: number;
    TakeOffWorkerId: number;
    TakeOffStatusId: number;
    LatheWorkerId: number;
    LatheStatusId: number;
    SetupWorkerId: number;
    SetupStatusId: number;
    CrewWorkerId: number;
    CrewStatusId: number;
    jobType: JobType;
    jobParts: JobPartModel[];
}
